public with sharing class MultiselectController {
   
    public SelectOption[] leftOptions { get; set; }
    public SelectOption[] rightOptions { get; set; }
    
  
    private void setOptions(SelectOption[] options, String value)
     {
    
    }
    

    public String leftOptionsHidden { get; set {
        
        }
    }
    
   
    public String rightOptionsHidden { get; set {
       
        }
    }
}